spec:
  replicas: 1
  template:
    spec:
      containers:
        - env:
            - name: JAVA_OPTIONS
              value: "-Dspring.profiles.active=openshift -Dnacos.server.address=nacos-service"
            - name: AB_JOLOKIA_OFF
              value: "true"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: HOSTNAME
              value: "user-service"
          readinessProbe:  
            tcpSocket:
              port: 20882
          livenessProbe:
            tcpSocket:
              port: 20882
              
