logging.level:
  com.alibaba.cloud.dubbo: warn
  org.apache.dubbo: warn

spring:
  application.name: user-service
  profiles.active: local

  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848

dubbo:
  protocol:
    name: dubbo
    port: 20882
  consumer:
    check: false
  cloud.subscribed-services: "fraud-verifier"

---
spring:
  config.activate.on-profile: openshift
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.server.address}:8848
      config:
        server-addr: ${nacos.server.address}:8848
