spec:
  replicas: 1
  template:
    spec:
      containers:
        - env:
            - name: JAVA_OPTIONS
              value: "-Dspring.profiles.active=openshift -Dnacos.server.address=nacos-service"
            - name: AB_JOLOKIA_OFF
              value: "true"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: HOSTNAME
              value: "card-service"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP

